#!/usr/bin/make -f

SPECIES=equus_caballus
GTF=Equus_caballus.EquCab2.80.gtf
FASTA=Equus_caballus.EquCab2.dna_sm.toplevel.fa

BOWTIE_INDEX_DIR=./
COMMON_MAKEFILE=../common_makefile

# include srr_makefile which has the rules for everything else
include ../srr_makefile

