#!/usr/bin/make -f

SPECIES=sus_scrofa
GTF=Sus_scrofa.Sscrofa10.2.80.gtf
FASTA=Sus_scrofa.Sscrofa10.2.dna.toplevel.fa

BOWTIE_INDEX_DIR=./
COMMON_MAKEFILE=../common_makefile

# include srr_makefile which has the rules for everything else
include ../srr_makefile

