#!/usr/bin/make -f

SPECIES=spalax_carmeli
ALIGNMENT_SPECIES=mus_musculus
GTF=../mouse/Mus_musculus.GRCm38.80.gtf
FASTA=../mouse/Mus_musculus.GRCm38.dna.toplevel.fa
BOWTIE_INDEX_DIR=../mouse/

COMMON_MAKEFILE=../common_makefile

include ../srr_makefile
