#!/usr/bin/make -f

SPECIES=monodelphis_domestica
GTF=Monodelphis_domestica.BROADO5.80.gtf.gz
FASTA=Monodelphis_domestica.BROADO5.dna.toplevel.fa

FASTQ_FILES=091125_lane_7_1.fastq.gz  091125_lane_7_2.fastq.gz

include ../common_makefile
