#!/usr/bin/make -f

SPECIES=papio_anubis
GTF=Papio_anubis.PapAnu2.0.80.gtf
FASTA=Papio_anubis.PapAnu2.0.dna.toplevel.fa

FASTQ_FILES=101116_lane_7_1.fastq 101116_lane_7_2.fastq


include ../common_makefile
