#!/usr/bin/make -f

SPECIES=dasypus_novemcinctus
GTF=Dasypus_novemcinctus.Dasnov3.0.80.gtf
FASTA=Dasypus_novemcinctus.Dasnov3.0.dna.toplevel.fa

FASTQ_FILES=armadillo_placenta_R1410_GTGAAA_L007_R1_001.fastq.gz armadillo_placenta_R1410_GTGAAA_L007_R2_001.fastq.gz

include ../common_makefile
