#!/usr/bin/make -f

SPECIES=ovis_aries
GTF=Ovis_aries.Oar_v3.1.80.gtf
FASTA=Ovis_aries.Oar_v3.1.dna.toplevel.fa

BOWTIE_INDEX_DIR=./
COMMON_MAKEFILE=../common_makefile

# include srr_makefile which has the rules for everything else
include ../srr_makefile

