#!/usr/bin/make -f

SPECIES=ateles_fusciceps
ALIGNMENT_SPECIES=callithrix_jacchus
GTF=Callithrix_jacchus.C_jacchus3.2.1.80.gtf
FASTA=Callithrix_jacchus.C_jacchus3.2.1.dna.toplevel.fa

FASTQ_FILES=R223_L4_1.fastq.gz R223_L4_2.fastq.gz

include ../common_makefile


